// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpe14VhJaviAcLbsGoHl_MvQAFFaAWmxA',
    appId: '1:798198071035:web:eef12ad4bff1f77f9cfa5e',
    messagingSenderId: '798198071035',
    projectId: 'ielts-gym-edbdf',
    authDomain: 'ielts-gym-edbdf.firebaseapp.com',
    storageBucket: 'ielts-gym-edbdf.appspot.com',
    measurementId: 'G-TR1ZC9WBEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf-aLRtpG3kjcvGtSTNc7uFgai01CS1qw',
    appId: '1:798198071035:android:00870b2b183029569cfa5e',
    messagingSenderId: '798198071035',
    projectId: 'ielts-gym-edbdf',
    storageBucket: 'ielts-gym-edbdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA14smCeLlNKWVNcvJt0AyAdEiTDajCeM8',
    appId: '1:798198071035:ios:0cc1026b58d78ba39cfa5e',
    messagingSenderId: '798198071035',
    projectId: 'ielts-gym-edbdf',
    storageBucket: 'ielts-gym-edbdf.appspot.com',
    iosBundleId: 'com.example.ieltsGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA14smCeLlNKWVNcvJt0AyAdEiTDajCeM8',
    appId: '1:798198071035:ios:0cc1026b58d78ba39cfa5e',
    messagingSenderId: '798198071035',
    projectId: 'ielts-gym-edbdf',
    storageBucket: 'ielts-gym-edbdf.appspot.com',
    iosBundleId: 'com.example.ieltsGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpe14VhJaviAcLbsGoHl_MvQAFFaAWmxA',
    appId: '1:798198071035:web:6b687be0bcacb4729cfa5e',
    messagingSenderId: '798198071035',
    projectId: 'ielts-gym-edbdf',
    authDomain: 'ielts-gym-edbdf.firebaseapp.com',
    storageBucket: 'ielts-gym-edbdf.appspot.com',
    measurementId: 'G-W44NWKVYDY',
  );
}
